# Generated by Django 2.1.7 on 2019-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190222_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count_of_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked', to='core.CustomUser'),
        ),
    ]
