# Generated by Django 2.1.7 on 2019-02-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190222_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='liked', to='core.CustomUser'),
        ),
    ]
